steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['pull', 'gcr.io/cartodb-on-gcp-ci-testing/cartodb-base:latest' ]

- name: 'gcr.io/cloud-builders/docker'
  args: ['pull', 'gcr.io/cartodb-on-gcp-ci-testing/cartodb-postgresql-base:10' ]

- name: 'gcr.io/cloud-builders/git'
  args: ['submodule', 'update', '--init', '--recursive']

